extends SceneTree
## Render the existing Blender characters for the Web dialogue without a world export.

func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	var viewport := SubViewport.new()
	viewport.size = Vector2i(192, 192)
	viewport.transparent_bg = true
	viewport.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	root.add_child(viewport)
	var world := Node3D.new()
	viewport.add_child(world)
	var env := WorldEnvironment.new()
	env.environment = Environment.new()
	env.environment.background_mode = Environment.BG_CLEAR_COLOR
	env.environment.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	env.environment.ambient_light_color = Color.WHITE
	env.environment.ambient_light_energy = .7
	world.add_child(env)
	var sun := DirectionalLight3D.new()
	sun.rotation_degrees = Vector3(-35, -30, 0)
	world.add_child(sun)
	var camera := Camera3D.new()
	camera.projection = Camera3D.PROJECTION_ORTHOGONAL
	camera.size = 1.8
	world.add_child(camera)
	camera.position = Vector3(0, 1.65, 4)
	camera.look_at(Vector3(0, 1.25, 0))
	var portraits := {}
	for id in ["coordinator", "coder", "teacher", "file_keeper"]:
		var model_name := "npc_keeper" if id in ["coordinator", "teacher"] else "npc_gardener" if id == "coder" else "npc_fisher"
		var model := load("res://assets/" + model_name + ".glb").instantiate() as Node3D
		world.add_child(model)
		await process_frame
		await RenderingServer.frame_post_draw
		await process_frame
		await RenderingServer.frame_post_draw
		var bitmap := viewport.get_texture().get_image().save_webp_to_buffer(false, .8)
		portraits[id] = "data:image/webp;base64," + Marshalls.raw_to_base64(bitmap)
		model.queue_free()
		await process_frame
	var output := FileAccess.open("res://../../packages/agent-isles-web/src/client/resident-portraits.ts", FileAccess.WRITE)
	output.store_string("// Generated by games/mosslight/tools/render_resident_portraits.gd from the Blender resident models.\nexport const RESIDENT_PORTRAITS = " + JSON.stringify(portraits, "  ") + " as const\n")
	output.close()
	print("RESIDENT_PORTRAITS_COMPLETE")
	quit()
