extends SceneTree
## Preserve authored dialogue portraits and generate the Web resident portrait map.

func _initialize() -> void:
	call_deferred("run")

func run() -> void:
	var dialogue_assets_only := "--dialogue-assets-only" in OS.get_cmdline_user_args()
	if dialogue_assets_only:
		if not FileAccess.file_exists("res://assets/portraits/gardener.png"):
			push_error("Authored gardener dialogue portrait is missing")
			quit(1)
			return
		print("DIALOGUE_PORTRAITS_PRESERVED")
		quit()
		return
	var portraits := {}
	portraits["coder"] = "/qcode/brand/q-portrait.png"
	portraits["coordinator"] = "/qcode/brand/teacher-portrait.png"
	portraits["teacher"] = "/qcode/brand/teacher-portrait.png"
	portraits["file_keeper"] = "/qcode/brand/file-keeper-portrait.png"
	var output := FileAccess.open("res://../../packages/qcode-web/src/client/resident-portraits.ts", FileAccess.WRITE)
	output.store_string("// Generated by games/mosslight/tools/render_resident_portraits.gd; dialogue portraits use authored illustrations.\nexport const RESIDENT_PORTRAITS = " + JSON.stringify(portraits, "  ") + " as const\n")
	output.close()
	print("RESIDENT_PORTRAITS_COMPLETE")
	quit()
